apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-tool
  labels:
    app: hr-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hr-tool
  template:
    metadata:
      labels:
        app: hr-tool
    spec:
      containers:
      - name: hr-tool
        image: hr-tool:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
